name: Fusion by Peter
baseurl: http://fusionplasma.co.uk
# baseurl: http://localhost:4000
description: my little presence on the web

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md']
